# Generated by Django 4.1.6 on 2023-11-14 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stade",
            fields=[
                (
                    "id_stade",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("capacite", models.IntegerField()),
                ("occupe", models.BooleanField(default=False)),
                ("image", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Equipe",
            fields=[
                (
                    "id_equipe",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("logo", models.CharField(max_length=200)),
                (
                    "situation",
                    models.CharField(
                        choices=[
                            ("interieur", "Intérieur"),
                            ("exterieur", "Extérieur"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "lieu",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="playground.stade",
                    ),
                ),
            ],
        ),
    ]
