# Generated by Django 4.1.6 on 2023-11-14 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0002_alter_equipe_logo_alter_stade_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipe",
            name="adversaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="playground.equipe",
            ),
        ),
    ]
