# Generated by Django 4.1.6 on 2023-11-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0009_alter_equipe_logo_alter_stade_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="adversaire",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="playground.equipe",
            ),
        ),
        migrations.AlterField(
            model_name="equipe",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="C:/Users/FOLIO/Desktop/ETUDE ECM/INFO_2/Projet_I2/logos/",
            ),
        ),
        migrations.AddConstraint(
            model_name="equipe",
            constraint=models.UniqueConstraint(
                fields=("adversaire",), name="unique_adversaire_per_equipe"
            ),
        ),
    ]
