# Generated by Django 4.1.6 on 2023-11-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0011_remove_equipe_unique_adversaire_per_equipe_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="logo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="C:/Users/FOLIO/Desktop/ETUDE ECM/INFO_2/Projet_I2/logos/",
            ),
        ),
        migrations.AlterField(
            model_name="stade",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="C:/Users/FOLIO/Desktop/ETUDE ECM/INFO_2/Projet_I2/stades/",
            ),
        ),
    ]
