# Generated by Django 4.1.6 on 2023-11-14 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0012_alter_equipe_logo_alter_stade_image"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="equipe",
            constraint=models.UniqueConstraint(
                fields=("adversaire",), name="unique_adversaire_per_equipe"
            ),
        ),
    ]
