# Generated by Django 4.1.6 on 2023-11-14 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0014_alter_equipe_logo_alter_stade_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stade",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="stades/"),
        ),
    ]
