# Generated by Django 4.1.6 on 2023-11-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playground", "0015_alter_stade_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipe",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
